SDL-Hercules-390/hyperion

- ctcadpt.c
- msgenu.h
Dear Fish,
Last week I completed testing of my last set of CTCE fixes, which contain some important bug fixes so that by now all available CTC test cases available to me are working flawlessly. And also CTC connections which already worked before will benefit from improved stability and recovery capabilities.
I implemented these CTCE improvements in all Hercules versions known to me, i.e. not only Spinhawk and Hyperion, but also for your SDL Hyperion version, which I admire very much, and which I took great care to test my CTCE corrections on. I thought this would be beneficial for all Hercules' users.
I would appreciate it if you could look at this, and if possible fulfill my "pull request". As usual, please feel free to comment, correct, or amend my work. 
Thanks and have a nice day ! …
> Additional CTCE bug fixes and stability and recovery improvements.

- .travis.yml
This is a retry of #137 which had to be scuttled due to #142.
The generic statements about [Travis CI](https://travis-ci.org) written in #137 stay of course valid.
The Regina issue was resolved with d73fe15, and the build succeed now, see [build 13](https://travis-ci.org/wfjm/hyperion/builds/423355312).
Before you decide to merge in this pull request your repository should be registered with  [Travis CI](https://travis-ci.org). Simply sign-in with your GitHub account. That sets up all the integration on the GitHub end (most notably the [webhook](https://developer.github.com/webhooks/) which triggers Travis builds). On the Travis side you have to enable the `hyperion` repository. That's all, the defaults work fine for this straightforward case.
At this point I stick with Regina-REXX. If …
> add continuous integration via Travis CI with .travis.yml

- console.c
This is a smallish change, so I just started the pull request without more ado.
I'm connecting a simulated terminal to a 70's-era hypertext system (FRESS) that runs under VM. In those days Brown University's VM installation (and I suspect most installations that had ASCII terminals) used custom translation tables, so that they could:
+ round trip ASCII<->EBCDIC
+ support ASCII terminal character sequences that included "weird" characters.
This change does two things:
1. It removes the filtering of "unprintable" characters from the network pipe.
&nbsp;
Standard telnet recognizes `\r\n` as the line end, but the raw characters can also be transmitted by the client without invoking that processing if the explicit escapes are used. (To solve my problem with the old VM code I would have to …
> Make console more faithful

- Hercules_VS2019.sln
- Hercules_VS2019.vcxproj
- msvc.makefile.includes/VSVERS.msvc
- vstools.cmd
- vsvers.h
The [build instructions](http://www.softdevlabs.com/hercules-vs2015-build.html) for SDL Hyperion document Visual Studio Community 2017, which is no longer easily (that I could find) available for download from Microsoft.  Visual Studio Community 2019 however is readily available.
These updates allow building the code using Visual Studio 2019.
First time using GitHub, so hoping what I've done is correct.
> Updates for Visual Studio 2019

- hthreads.c
Create copy of thread name on heap to prevent pointer reference on callers stack being used. 
Free heap area for name after use.
> Fix issue where thread names are incorrectly set

- archlvl.c
- msgenu.h
- tests/mainsize.tst
Correct spelling of "minimum" and "maximum" in HHC17006W messages, and the tests that look at those messages.
> Correct spelling in msgs

- util/bldlvlck
Update minimum required / recommended tools to aid building more smoothly across various Linux distributions.
Update minimum required 'gcc' from (the ancient) version 3, to (a still pretty old, but modern) 4.6.2.
Add requirement for 'ld', as this was found missing from some Linux distributions.
Add requirement for 'cmake'.
> Aid building more smoothly on Linux

- ccnowarn.h
Add check for GCC version 7.1 or higher before disabling the -Wformat-truncation warning.
> Skip for GCC below 7.1 - DISABLE_GCC_WARNING( "-Wformat-truncation" )

- util/bldlvlck
Suggest a different gcc version (6.3.0) as the minimum requirement for 32-bit i686 systems.
This is required to get working atomics and pass the CBUC test.
64-bit system work correctly with the existing older minimum version, which is unchanged.
> Split out gcc version check for 32-bit i686 vs others

- _dynamic_version
- util/bldlvlck
NetBSD doesn't keep Bash in /bin, so we use the 'env' program to find it.
Special case the 'gcc' detection.
Special case the 'm4' detection.
Special case the 'sed' detection, to remove error messages, but not actually detect the version.
This is part of ongoing work to get the build working on NetBSD.
> Build netbsd

- console.c
The device lock is held when this call is made and if it blocks
things go down hill in a hurry.  According to the Linux select(2)
man page a call to recv may block even a previous call to select
says it shouldn't.  This has also been seen on MacOSX.
This fixes issue 377
> Make the call to recv on the telnet connection non-blocking.

- autoconf/config.rpath
- autoconf/libtool.m4
- configure.ac
The autoconf/automake, etc. included with Hercules are 15 to 20 years out of date and were never set up to handle newer FreeBSD properly.  As a result shared libraries and linking are not handled.  This change addresses that.
> Corrections to autoconf for BSD 12 shared libraries

- util/bldlvlck
Recent changes to improve performance of inlined functions require gcc 5 or greater (to get the desired behavior by default).
> Bump minimum gcc version to 5 for proper "inline" behavior

- .gitignore
For those of us using Bill Lewis's excellent `hercules-helper` script to build and install, this will tell git to ignore the build directory it uses inside the Hyperion tree.
> Ignore hercules-helper's build directory.

- ctcadpt.h
The LCS support code as committed refuses to build with gcc on Linux because three functions are defined as static in `ctc-lcs.c` and not as static in `ctcadapt.h`.  Since those functions are not used outside of `ctc-lcs.c`, there's no need to define them in `ctcadapt.h`, so the easiest way to fix the error is simply to remove the definitions from the header file.
> Fix gcc compile error on Linux in the LCS SNA support code.

- hmacros.h
When using `setuid`, it's important to set the group permissions first to avoid a potential security issue. See https://wiki.sei.cmu.edu/confluence/display/c/POS36-C.+Observe+correct+revocation+order+while+relinquishing+privileges for details.
> Ensure setgid is called before setuid

- util/Makefile.am
voldsext.cmd is only useful on Windows. Similarly to others scripts under util/, don't install it as a binary but just include it in the distribution.
> Do not install voldsext.cmd

- assist.c
- opcode.c
- opcode.h
This request adds the ADDFRR MVS assist from the 3033 Extensions feature.
> Add ADDFRR MVS assist

- inline.h
gcc 10 warns many times like so:
```
CC       chsc.lo
In file included from hercules.h:105,
from chsc.c:21:
hinlines.h:342:33: warning: 'Release_Interrupt_Lock' is static but used in inline function 's370_per1_gra' which is not static
342 | #define RELEASE_INTLOCK(r)      Release_Interrupt_Lock( r, PTT_LOC )
|                                 ^~~~~~~~~~~~~~~~~~~~~~
inline.h:555:5: note: in expansion of macro 'RELEASE_INTLOCK'
555 |     RELEASE_INTLOCK( regs );
|     ^~~~~~~~~~~~~~~
hinlines.h:341:33: warning: 'Obtain_Interrupt_Lock' is static but used in inline function 's370_per1_gra' which is not static
341 | #define OBTAIN_INTLOCK(r)       Obtain_Interrupt_Lock( r, PTT_LOC )
|                                 ^~~~~~~~~~~~~~~~~~~~~
inline.h:550:5: note: in expansion of macro …
```
> Make an inline function also static.

- cckddasd.c
- config.c
- dasdload2.h
- hRexx.c
- hostopts.h
- hthreads.c
- impl.c
- msgenu.h
- printfmt.h
- tcpnje.c
- tfprint.c
I put every type of warning in a different commit, together with the actual warning message, so it should be clear what is what, and it can be cherry-picked if desired.
With these patches, there are no compiler warnings any more on my system (except the getrusage one from #573).
(There are some linker warnings about "/usr/bin/ld: /usr/lib/libc.so and /usr/lib/crt0.o: warning: multiple common of environ" but I suspect that may be too NetBSD specific, and in any case I didn't look into it yet)
> Fix remaining warnings

- cgibin.c
- httpmisc.h
- httpserv.c
This change adds JSON APIs to the HTTP server similar to xml/rate but provides a lot more information in different/various API calls. 
This request adds the following URLs:
- cgi-bin/api/v1 - returns JSON with information about the APIs
- cgi-bin/api/v1/cpus - Returns JSON with information about the CPUs
- cgi-bin/api/v1/devices - Returns JSON with information about the configured devices
- cgi-bin/api/v1/rates - Returns JSON with MIPS/IO
- cgi-bin/api/v1/maxrates - Returns JSON with maxrates information
- cgi-bin/api/v1/version - Returns JSON with version information
- cgi-bin/api/v1/storage - Returns JSON with storage at an address ( a parameter, default 0) of fullword (a parameter, default 32) length
- cgi-bin/api/v1/syslog - Returns JSON of the syslog, each line in an array. Can take …
> Adding JSON APIs to the HTTP server

- comm3705.c
If a 3705 device is attached, detached, and attached again, Hercules crashes to desktop.
Reproduce:
```
attach 590 3705 lport=3705
detach 590
attach 590 3705 lport=3705
```
The DEVBLK was never being marked as in use and needing closing. Code did reset the dev->fd to -1 to indicate it was no longer in use, and checked it, but never actually set it. Since the fd isn't used for anything but this purpose, it'ss et to a nonsense positive value.
> Fix 3705 crash on attach/detach/attach.

- hscemode.c
- hstructs.h
- opcode.h
In preparation for possible changes that may become necessary for the vector facility (129) and as a practical exercise of how pulls requests work in this project, I request these changes in the behavior of icount:
1.- Counters & times tables in hstructs.h & opcode.h for E7xx instruction family.
2.- Add PRINT_INST to ouput line
```
hscemode.c(2865)  HHC02292I Sorted icount display: 
hscemode.c(2912)  HHC02292I Inst 'E371' count            2 (28%) time          617 (308.500000) LAY   0,0(0,0)               load_address_y  
hscemode.c(2912)  HHC02292I Inst 'A704' count            1 (14%) time            5 (  5.000000) BRC   0,*+0                  branch_relative_on_condition                   
hscemode.c(2912)  HHC02292I Inst '05'   count            1 (14%) time          724 (724.000000) …
```
> ICOUNT changes to accomodate E7xx family, PRINT_INST & qsort

- hscmisc.c
- hstructs.h
- logger.c
Here is a 2nd solution to fix two log format issues during shutdown [Issue 480:](https://github.com/SDL-Hercules-390/hyperion/issues/480)
1. duplicate log lines on non-Windows systems.
Issue related to logger processing and timing of shutdown `logger_unredirect()`. To fix the timing issue, a system `shutbegin` flag notifies `logger_thread()` that shutdown is beginning and to execute  `logger_unredirect()` before setting system shutdown flag. Timing is now controlled by `logger_thread()`.
2. interleaved log lines with two time stamps or missing a timestamp.
Update `logger_timestamped_logfile_write` to have a lock if timestamps are required. 
Tested using MVS TK5 startup/shutdown on Armbain Jammy (Ubuntu) on Raspberry Pi4 and Intel Nuc, and on Windows (Intel Nuc). Missing log lines _(e.g. …
> Log format during shutdown (Issue 480)

- hscmisc.c
- logger.c
- msgenu.h
- panel.c
Fish,
The request handles two items:
1. replaces clean_screen() in panel_cleanup with blank_panel() to fix Issue 645.
2. adds some synchronization, controlled by hsmisc.c, between logger and panel. This synchronization improves terminal console message capture at shutdown. A new message 'HHC01421I Shutdown: %s' has been added.
Sorry, I should have separated this into two commits. 
I've tested the request on my Linux system and on Windows (only very basic tests). On my Linux system with Regina Rexx, 'make check' completes.
Again, the request need your review, and maybe some testing by Bill on other OS's.
Jim
> Terminal session output during shutdown (Issue 645)

- instfmts.h
- zvector2.c
Fish,
Here is the latest update for the Z/Vector E6 instructions for your critical 'instructor' review. The first commit is an update to an instruction decoder, just wrong, wrong on my part.   zvector2.c now has my first cut for all non-floating point instructions (I have moved these instructions to the end of zvecto2.c).  decNumber is now used for all packed decimal arithmetic operations.
The next tasks are tests and more tests but I'm going to take a break for a couple of weeks.
Thanks for your review and comments.
Jim
> Zvector E6 instruction updates 

- autoconf/hercules.m4
- configure.ac
This is needed for gcc 14 and clang 16 as they both make implicit function definitions a hard error.  In a configure script, this means these tests will switch from passing to failing, which likely means features will get unintentionally flipped as configure now thinks you don't have support.
See: https://wiki.gentoo.org/wiki/Modern_C_porting
See: https://bugs.gentoo.org/931607
> Add missing includes to configure script

- configure.ac
If the user specifies an external location for the 4 helper libraries, do not append any architecture name when creating the lib path. That is used only when the libraries are used which are delivered with the repository.
> Obey value of --enable-extpkgs option.

- impl.c
As per Hercules-Helper, 'make check' 
```
Be patient, this can take a while with no output.
If you check top/htop and nothing seems to be happening, 
try hitting Return or CTRL+D.
```
I frequently use 'make check'. On my Raspberry PI 5 with Ubuntu 24.04, I always have to remember a ctrl-d.  It's finally becoming annoying. So, I am proposing this change. 
But, as I know nothing about, or how people may using, 'daemon mode without any external GUI...', I'm looking for comments/further review.
Thanks,
Jim
> Remove possible requirement for a ctrl-d to finish a 'Make Check'

- autoconf/hercules.m4
1. withoug "--tag", libtool will:
libtool:   error: specify a tag with '--tag'
libtool: compile: unable to infer tagged configuration
2. without "extern ...", compile will:
error: implicit declaration of function 'getopt'
error: implicit declaration of function 'test1'
both will cause false postive of feature test, i.e.,
"checking whether getopt wrapper kludge is necessary" report yes always
then config.h always has "#define NEED_GETOPT_WRAPPER 1".
In fact, redirect all output to /dev/null hide many information (some are unexpected in any case).
> autoconf/hercules.m4: fix compiling error w/ modern C duing configure

- cckd.h
- cckddasd.c
- cckddasd.h
- cckddasd64.c
- cmdtab.h
- hthreads.h
- html/cckddasd.html
- msgenu.h
This PR adds a DASD Hardener thread as discussed at https://github.com/SDL-Hercules-390/hyperion/issues/701#issuecomment-2620060471, to solve the problem of potentially very long delays between guest OS DASD writes and Herules writes to disk.
**Note:** Although the updates to the documentation in this PR recommend settting CCKD DHINT > 0 and CCKD FSYNC=1, this update _does not_ set those as defaults.  I'm open to doing so, but it seemed like defaulting this code to "active" was a big first step.
> Fix #701 (long delays to harden CCKD DASD) 

- machdep.h
The CSDG instruction is defined as succeeding if the target location contains the expected value.
A LL/SC pair without a retry loop can cause a spurious failure if something (scheduler interrupt, write to an adjacent location, etc) causes the cpu to lose the exclusive access after comparison, but before the store. Notably, this causes memory corruption on linux after commit 6801be4f, which started using CDSG for SLUB freelist management. On my M1 Pro (taskset-ed to only P-cores), it results in a kernel panic either during boot, or shortly after qeth drivers get probed.
> Fix CDSG on aarch64.
